export type CaseItem = {
  id: string;
  archetype: string;
  industria: string;
  area: string;
  caso: string;
  problema: string;
  solucion: string;
  roi: string;
  tools: string;
  prio: 1 | 2 | 3;
};

export const CASES: CaseItem[] = [
  {
    id: "D-01",
    archetype: "Distribuidora con SAP y red de distribuidores",
    industria: "Distribucion",
    area: "Atencion a Clientes",
    caso: "Agente de toma de pedidos multicanal",
    problema: "El equipo captura pedidos manualmente desde correo, WhatsApp y llamadas.",
    solucion: "Un agente de IA extrae pedidos, valida inventario en ERP y confirma al cliente automaticamente.",
    roi: "Eliminar captura manual y desbloquear ventas 24/7 con ROI menor a 6 meses.",
    tools: "SAP API, WhatsApp Business API y reglas de negocio sobre LLM.",
    prio: 1,
  },
  {
    id: "D-02",
    archetype: "Distribuidora con servicio tecnico propio",
    industria: "Distribucion",
    area: "Servicio Tecnico",
    caso: "Filtro inteligente de tickets de soporte",
    problema: "El equipo tecnico atiende consultas repetitivas que no requieren escalamiento.",
    solucion: "Un agente realiza diagnostico inicial y escala solo fallas reales.",
    roi: "Reducir mas de 50% los tickets al tecnico y mejorar tiempo de respuesta.",
    tools: "WhatsApp o web chat, arbol de diagnostico e integracion con ticketing.",
    prio: 1,
  },
  {
    id: "D-03",
    archetype: "Distribuidora con despacho B2B",
    industria: "Distribucion",
    area: "Logistica",
    caso: "Notificaciones proactivas de estatus de pedido",
    problema: "Clientes preguntan manualmente por pedidos y saturan atencion.",
    solucion: "Agente conectado a ERP y paqueterias envia estatus proactivo y responde en tiempo real.",
    roi: "Menos llamadas entrantes y mejor satisfaccion del cliente.",
    tools: "APIs de paqueterias y WhatsApp Business API.",
    prio: 1,
  },
  {
    id: "D-04",
    archetype: "Distribuidora con multiples fleteras",
    industria: "Distribucion",
    area: "Finanzas",
    caso: "Auditoria automatica de facturas de fleteras",
    problema: "Discrepancias de cobro se detectan tarde y su revision es manual.",
    solucion: "Un agente cruza facturas contra pedidos y tarifarios para detectar cobros incorrectos.",
    roi: "Recuperacion de dinero desde el primer mes y proceso en minutos.",
    tools: "OCR en PDF, reglas tarifarias y flujos automatizados.",
    prio: 1,
  },
  {
    id: "D-05",
    archetype: "Distribuidora con red y catalogo amplio",
    industria: "Distribucion",
    area: "Ventas",
    caso: "Analisis predictivo por SKU y zona",
    problema: "Caidas de venta se detectan tarde por analisis manual.",
    solucion: "Monitoreo en tiempo real con alertas por distribuidor, zona y familia de producto.",
    roi: "Recuperar ventas perdidas y enfocar al equipo comercial.",
    tools: "Datos ERP, deteccion de anomalias y alertas por correo o WhatsApp.",
    prio: 1,
  },
  {
    id: "M-01",
    archetype: "Fabricante con pedidos por WhatsApp y correo",
    industria: "Manufactura",
    area: "Ventas",
    caso: "Sistema digital de captura de pedidos",
    problema: "Pedidos sin registro central y nula visibilidad de pendientes.",
    solucion: "Flujo digital de captura conectado a inventario para generar orden de produccion o despacho.",
    roi: "Eliminar errores de pedidos y mejorar forecast de produccion.",
    tools: "Portal web o WhatsApp Business API integrado a ERP.",
    prio: 1,
  },
  {
    id: "M-02",
    archetype: "Fabricante con cartera de credito",
    industria: "Manufactura",
    area: "Finanzas",
    caso: "Control de cuentas por cobrar con semaforos",
    problema: "Clientes vencidos siguen recibiendo producto por falta de control central.",
    solucion: "Semaforos automaticos bloquean pedidos fuera de politica y disparan recordatorios por antiguedad.",
    roi: "Recuperar cartera y reducir riesgo de credito incobrable.",
    tools: "Modulo CxC conectado a ventas y alertas por WhatsApp.",
    prio: 1,
  },
  {
    id: "M-03",
    archetype: "Fabricante con inventario desalineado",
    industria: "Manufactura",
    area: "Operaciones",
    caso: "Conciliacion de inventario fisico vs contable",
    problema: "Diferencias de inventario se acumulan y afectan margenes reales.",
    solucion: "Registro en tiempo real por lote con alertas ante desviaciones.",
    roi: "Visibilidad real de margenes y deteccion temprana de merma o error.",
    tools: "Registro en tablet/codigo de barras y WMS ligero o custom.",
    prio: 1,
  },
  {
    id: "M-04",
    archetype: "Fabricante sin estados financieros oportunos",
    industria: "Manufactura",
    area: "Finanzas",
    caso: "Estados financieros automatizados en tiempo real",
    problema: "La direccion decide con informacion atrasada y construida manualmente.",
    solucion: "Modulo financiero conectado a operaciones para estado de resultados, balance y flujo al dia.",
    roi: "Mejor acceso a credito y decisiones con datos vigentes.",
    tools: "Base operativa centralizada y modulo contable integrado.",
    prio: 1,
  },
  {
    id: "M-05",
    archetype: "Fabricante con lineas configurables",
    industria: "Manufactura",
    area: "Produccion",
    caso: "Alimentacion proactiva de lineas de produccion",
    problema: "Lineas con backlog y paros por asignacion manual de trabajo.",
    solucion: "Asignacion automatica segun capacidad por turno y backlog en tiempo real.",
    roi: "Mejor OEE y menos tiempo muerto entre operaciones.",
    tools: "Pantallas en piso y dashboard de capacidad por linea.",
    prio: 2,
  },
  {
    id: "S-01",
    archetype: "Empresa de servicios con pedidos por WhatsApp",
    industria: "Servicios",
    area: "Ventas",
    caso: "Cotizacion automatica de servicios personalizados",
    problema: "Cada cotizacion requiere trabajo manual y hay errores de precio.",
    solucion: "Configurador inteligente que genera cotizacion automatica segun reglas del negocio.",
    roi: "Reducir tiempo de cotizacion de horas a minutos.",
    tools: "Configurador web/WhatsApp con logica de precios conectada.",
    prio: 1,
  },
  {
    id: "S-02",
    archetype: "Empresa de servicios con atencion por WhatsApp",
    industria: "Servicios",
    area: "Atencion a Clientes",
    caso: "Agente de servicio al cliente 24/7",
    problema: "Respuestas no estandarizadas y seguimiento inconsistente.",
    solucion: "Agente entrenado en procesos responde consultas frecuentes y escala casos de criterio.",
    roi: "Atencion estandarizada 24/7 con menor carga humana.",
    tools: "WhatsApp Business API, CRM y base de conocimiento.",
    prio: 1,
  },
  {
    id: "A-01",
    archetype: "Acopiador de granos con transporte masivo",
    industria: "Agrocomercio",
    area: "Operaciones",
    caso: "Validacion automatica de boletas de transporte",
    problema: "Boletas duplicadas o alteradas se validan manualmente con alto riesgo financiero.",
    solucion: "Comparacion automatica entre boleta origen, destino y factura con bloqueo de pago ante discrepancias.",
    roi: "Prevencion de perdidas y validaciones en minutos.",
    tools: "OCR sobre fotos y reglas de validacion contra base historica.",
    prio: 1,
  },
];
